---
config:
  theme: 'base'
  gitGraph:
    mainBranchName: "time"
    mainBranchOrder: 4
    parallelCommits: false
    rotateCommitLabel: false
  themeVariables:
      git0: '#ff9c03' # work
      git1: '#04c5c2' # misc
      git2: '#03b3ff' # pet project
      git3: 'grey'    # time
      commitLabelFontSize: "8px"
---
gitGraph TB: %%LR:
    branch "work" order:1
    branch "pet project" order:3
    checkout "time"
    commit id:"long time ago"

    checkout "work"
    commit id:"architect @ big corp" type:HIGHLIGHT

    %% ------------------------------- 2016
    checkout "time"
    commit id:"2016"
    %% ------------------------------------

    %% ------------- Start pet project
    checkout "time"
    checkout "pet project"
    commit id:"🤙 idea"
    %% ------------------------------------

    checkout "pet project"
    commit id:"Play framework" type:HIGHLIGHT

    checkout "pet project"
    commit id:"scala"

    checkout "work"
    commit id:"dev @ startup" type:HIGHLIGHT

    checkout "work"
    merge "pet project" id:"Spark"

    %% ------------------------------- 2017
    checkout "time"
    commit id:"2017"
    %% ------------------------------------

    checkout "time"
    commit id:"👶 baby" type:HIGHLIGHT

    %% --------------------------- Scala.io
    checkout "work"
    merge "pet project" id:"Scala.io conf"
    %% ------------------------------------

    checkout "pet project"
    commit id:"ScalaJs"

    %% ------------------------------- 2018
    checkout "time"
    commit id:"2018"
    %% ------------------------------------

    checkout "work"
    commit id:"Typescript"
    checkout "pet project"
    merge "work"
    commit id:"Angular" type:HIGHLIGHT
    commit id:"Ionic" type:HIGHLIGHT

    checkout "work"
    commit id:"MongoDb"

    checkout "pet project"
    merge "work" id:"MeteorJS" type:HIGHLIGHT

    %% ---------------------------- Start Criteo
    checkout "work"
    commit id:"dev @ Criteo" type:HIGHLIGHT
    checkout "time"
    merge "work"

    commit id:"🏡 rent a house" type:HIGHLIGHT

    %% ------------------------------- 2019
    checkout "time"
    commit id:"2019"
    %% ------------------------------------

    checkout "work"
    merge "pet project" id:"CGrowth UI"

    %% ------------------------------- 2020
    checkout "time"
    commit id:"2020"
    %% ------------------------------------

    checkout "pet project"
    commit id:"Leaflet"

    checkout "work"
    merge "pet project" id:"Geoloc audiences"

    %% checkout "pet project"
    %% commit id:"notifications"

    %% checkout "work"
    %% merge "pet project" id:"CGrowth alerts"

    %% ------------------------------- 2021
    checkout "time"
    commit id:"2021"
    %% ------------------------------------

    checkout "work"
    commit id:"User Data Platform"

    checkout "pet project"
    commit id:"github actions"

    checkout "work"
    merge "pet project" id:"OneKey"

    checkout "pet project"
    commit id:"data validation - strong typing"

    branch "misc" order:2
    commit id:"schema-to-types" %% remove-start

    checkout "work"
    merge "misc" id:"JSON schemas"

    checkout "pet project"
    merge "misc"

    checkout "misc"
    merge "pet project" id:"consulting" %% remove-end %% remove-start

    %% ------------------------------- 2022
    checkout "time"
    commit id:"2022"
    %% ------------------------------------

    checkout "pet project"
    merge "misc"

    %% checkout "pet project"
    %% commit id:"open data"
    %% commit id:"web crawler"

    checkout "misc"
    merge "pet project" id:"waterspot-catalog" %% remove-end %% remove-start
    checkout "pet project"
    merge "misc"

    %% ------------------------------- 2023
    checkout "time"
    commit id:"2023"
    %% ------------------------------------

    %% ---------------------- Place to live
    checkout "misc"
    merge "pet project" id:"a-place-to-live" %% remove-end %% remove-start
    checkout "pet project"
    merge "misc"
    %% ------------------------------------

    checkout "time"
    merge "misc" id:"🏡 buy a house" type:HIGHLIGHT

    %% checkout "pet project"
    %% commit id:"ImageKit"

    %% ------------------------------- 2024
    checkout "time"
    commit id:"2024"
    %% ------------------------------------

    checkout "pet project"
    commit id:"open graph"

    checkout "pet project"
    commit id:"SSR"

    checkout "work"
    commit id:"Dev lead" type:HIGHLIGHT

    %% ------------------------------- 2025
    checkout "time"
    commit id:"2025"
    %% ------------------------------------

    %% checkout "work"
    %% merge "pet project" id:"client metadata"

    checkout "misc"
    merge "pet project" id:"talk" %% remove-end
    commit id:"reveal.js"
    commit id:"emmet"
    commit id:"mermaid.js"
    commit id:"sozi"
    commit id:"github pages"

    checkout "work"
    merge "misc" id:"🎤 futurise"

    checkout "time"
    commit id:" "