---
config:
  theme: 'base'
  gitGraph:
    mainBranchName: "time"
    mainBranchOrder: 4
    parallelCommits: false
---
gitGraph TB: %%LR:
    branch "work" order:1
    checkout "time"
    commit id:"long time ago"

    %% ------------------------------- 2016
    checkout "time"
    commit id:"2016"
    %% ------------------------------------

    checkout "time"
    checkout "work"
    commit id:"adtech startup" type:HIGHLIGHT

    %% ------------- Start pet project
    checkout "time"
    branch "pet project"  order:3
    checkout "pet project"
    commit id:"🤙 idea"
    commit id:"Play framework" type:HIGHLIGHT
    %% ------------------------------------

    branch "misc" order:2
    checkout "misc"
    commit id:"scala"
    
    checkout "work"
    merge "misc" id:"Spark"

    %% ------------------------------- 2017
    checkout "time"
    commit id:"2017"
    %% ------------------------------------
    
    checkout "misc"
    commit id:".grib files"
    
    checkout "work"
    commit id:"MongoDb"
    
    checkout "pet project"
    merge "work" id:"MeteorJS" type:HIGHLIGHT
    
    merge "misc" id:"Ionic"
    
    %% ------------------------------- Baby
    checkout "time"
    commit id:"👶 baby" type:HIGHLIGHT
    %% ------------------------------------

    %% ------------------------------- 2018
    checkout "time"
    commit id:"2018"
    %% ------------------------------------

    %% --------------------------- Scala.io
    checkout "work"
    merge "misc" id:"Scala.io conference"
    %% ------------------------------------
    
    %% ---------------------------- Start Criteo
    checkout "work"
    commit id:"Criteo" type:HIGHLIGHT
    checkout "time"
    merge "work" id:"👔 new job" type:HIGHLIGHT

    commit id:"🏡 rent a house" type:HIGHLIGHT
    
    %% ------------------------------- 2019
    checkout "time"
    commit id:"2019"
    %% ------------------------------------

    checkout "pet project"
    commit id:"Angular"
    commit id:"Typescript"

    checkout "work"
    merge "pet project" id:"CGrowth UI"

    %% ------------------------------- 2020
    checkout "time"
    commit id:"2020"
    %% ------------------------------------
    
    checkout "pet project"
    commit id:"Leaflet"
    
    checkout "work"
    merge "pet project" id:"Geoloc audiences"

    checkout "pet project"
    commit id:"notifications"

    checkout "work"
    merge "pet project" id:"CGrowth alerts"

%% ------------------------------- 2021
    checkout "time"
    commit id:"2021"
    %% ------------------------------------

    checkout "pet project"
    commit id:"github actions"

    checkout "work"
    merge "pet project" id:"OneKey"


    checkout "pet project"
    commit id:"data validation"
    commit id:"strong typing"


    checkout "misc"
    merge "pet project" id:"schema-to-types"

    checkout "work"
    merge "misc" id:"JSON schemas"
    
    checkout "pet project"
    merge "misc"

    %% ------------------------------- 2022
    checkout "time"
    commit id:"2022"
    %% ------------------------------------
    
    checkout "misc"
    merge "pet project" id:"consulting"

    checkout "pet project"
    merge "misc"

    %% ------------------------------- 2023
    checkout "time"
    commit id:"2023"
    %% ------------------------------------
    
    checkout "pet project"
    commit id:"open data"
    commit id:"web crawler"
    
    checkout "misc"
    merge "pet project" id:"waterspot-catalog"
    checkout "pet project"
    merge "misc"

    %% ---------------------- Place to live
    checkout "misc"
    merge "pet project" id:"a-place-to-live"
    checkout "pet project"
    merge "misc"
    %% ------------------------------------

    checkout "time"
    merge "misc" id:"🏡 buy a house" type:HIGHLIGHT

    checkout "pet project"
    commit id:"ImageKit"

    %% ------------------------------- 2024
    checkout "time"
    commit id:"2024"
    %% ------------------------------------

    checkout "pet project"
    commit id:"open graph"

    checkout "pet project"
    commit id:"server side rendering"

    %% ------------------------------- 2025
    checkout "time"
    commit id:"2025"
    %% ------------------------------------

    checkout "work"
    commit id:"🎤 futurise"