name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: npm install

      - name: Build with Gulp
        run: npx gulp build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
